development:
  user: radmin
  password: 9K7mNOKBDgo
production:
  # user:  <%= ENV["ADMIN_USER_NAME"] %>
  # password: <%= ENV["ADMIN_PASSWORD"] %>
  user: ENV["ADMIN_USER"]
  password: ENV["ADMIN_PASSWORD"]
